[package]
name = "rocket"
version = "0.1.0"
authors = ["Edward Partenie <edward.partenie@gmail.com>"]

[[bin]]
name = "rocket"

[dependencies]
piston = "0.19.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.23.0"
piston2d-opengl_graphics = "0.26.0"
find_folder = "0.3.0"
